# https://docs.readthedocs.io/en/stable/config-file/v2.html
---
version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - help2man
    - pandoc
  tools:
    python: "3"

formats: all

python:
  install:
    - requirements: docs/requirements.txt
