---
name: translate-shell
description: Translate .po of one repo
inputs:
  files:
    description: files need to be translated, support glob
    default: "**/*.po"
  target-lang:
    description: target language, po's metadata's Language override it
    default: zh_CN
  source-lang:
    description: source language
    default: en
  translator:
    description: translator
    default: google
  option:
    description: >
      the option passed to translator, such as 'temperature=0 max_tokens=256'
  wrapwidth:
    description: wrap the width by polib
    default: "76"
  progress:
    description: display progress of translation
    default: "false"
  verbose:
    description: display diff of translation
    default: "true"
  dry-run:
    description: do nothing
    default: "false"
  force:
    description: force to retranslate translated po
    default: "false"
branding:
  icon: check
  color: yellow
runs:
  using: docker
  image: Dockerfile
