#!/usr/bin/env bash
cd "$(dirname "$(dirname "$0")")/src" || exit 1
if [[ $1 == --help ]]; then
	python -m translate_shell --help |
		perl -pe's/(options|positional arguments):/\nOptions:/g;s/usage:/Usage:/' |
		perl -p0777 -e's/\n\s+\[/ [/gs'
else
	python -m translate_shell "$@"
fi
