---
"on":
  push:
    paths-ignore:
      - "**.md"
      - docs/*
  pull_request:
    paths-ignore:
      - "**.md"
      - docs/*
  workflow_dispatch:

env:
  python-version: 3.x
  cache: pip
  themis: vim-themis/bin/themis

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        neovim:
          - true
          - false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: ${{ env.cache }}
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
      - name: Install dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install shfmt
      - name: Install dependencies for macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install shellcheck shfmt
      - name: Install dependencies
        run: |
          pip install -e '.[dev]'
      - name: Test for Linux and macOS
        if: runner.os != 'Windows'
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          make THEMIS=$themis test
      - name: Test for Windows
        if: runner.os == 'Windows'
        run: |
          $themis
          pytest --cov
      - uses: codecov/codecov-action@v3
  build:
    needs: test
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: ${{ env.cache }}
      - name: Install dependencies
        run: |
          pip install build
      - name: Build
        run: |
          python -m build
      - uses: actions/upload-artifact@v3
        if: runner.os == 'Linux' && ! startsWith(github.ref, 'refs/tags/')
        with:
          path: |
            dist/*
            build/resources/*
      - uses: softprops/action-gh-release@v1
        if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*
            build/resources/*
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
