---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        nixpkgs:
          - nixos-unstable
          - nixpkgs-unstable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:${{matrix.nixpkgs}}
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{secrets.GITHUB_TOKEN}}
      - name: Build
        run: |
          nix build
